# Generated by Django 4.1.7 on 2023-03-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('director', models.CharField(max_length=120)),
                ('genre', models.CharField(max_length=120)),
                ('synopsis', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
