# Generated by Django 4.1.7 on 2023-03-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='nationality',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='actor',
            name='nominations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
