# Generated by Django 4.1.7 on 2023-03-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_actor_nationality_actor_nominations_director_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
