# Generated by Django 4.1.7 on 2023-03-19 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_movieactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieactor',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='api.actor'),
        ),
    ]
