# Generated by Django 4.1.7 on 2023-03-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_actor_movies_remove_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(through='api.MovieActor', to='api.movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='api.MovieActor', to='api.actor'),
        ),
    ]
